# Dependencies
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
#  - thumbnail
  - mini_magick
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

excerpt_separator: <!--more-->

# Setup
title:            blogJS
tagline:          'JavaScript blog by Anton Temchenko'
description:      'JavaScript blog with tips, reviews, and functionality-understanding articles.'
url:              http://blogjs.github.io
baseurl:          /
twitter_username: antontemchenko
github_username:  antontemchenko
email: anton@temchenko.com.ua

author:
  name:           'Anton Temchenko'
  url:            http://anton.temchenko.com.ua

paginate:         5

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/blogjs/blogjs.github.io
